version: "3.7"
services:
    disney-landing-page:
        image: cnt/disney-landing-page:1.0
        ports:
            - 9193:8080
        environment:
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_PORT: ${DB_PORT}            
            DB_SM_HOST: ${DB_HOST}
            DB_SM_DATABASE: ${DB_DATABASE}
            DB_SM_USER: ${DB_USER}
            DB_SM_PASSWORD: ${DB_PASSWORD}
            DB_SM_PORT: ${DB_PORT}            
            DB_FI_HOST: ${DB_HOST}
            DB_FI_DATABASE: ${DB_DATABASE}
            DB_FI_USER: ${DB_USER}
            DB_FI_PASSWORD: ${DB_PASSWORD}
            DB_FI_PORT: ${DB_PORT}                        
networks:
  dev_default:
    name: dev_default
    external: true
    