version: "3.7"
#Levanta un ambiente de funcional de Qoopo con una base nueva

services:
#Base de Datos    
    db:
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: facturacion
            POSTGRES_USER: facturacion
            POSTGRES_DB: facturacion

    qoopo-facturacion-ear:
        image: qoopo/facturacion-ear:1.0
        build: ./
        ports:
            - 6060:8080
        environment:
            DB_HOST: db
            DB_DATABASE: facturacion
            DB_USER: facturacion
            DB_PASSWORD: facturacion
            DB_PORT: 5432