version: "3.7"
services:
    qoopo-facturacion-ear:
        image: qoopo/facturacion-ear:1.0
        ports:
            - 8080:8080
        environment:
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_PORT: ${DB_PORT}                                        
networks:
  dev_default:
    name: dev_default
    external: true
    